name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build data
      run: |
        # Check if raw data exists, if not create a sample or skip
        if [ -f "raw/merged_spotify_data.json" ]; then
          npm run build:data
        else
                     echo "No raw data found, creating sample data for demo..."
           mkdir -p docs/data
           # Create proper sample data
           echo '{"total_ms": 3600000, "total_hours": 1.0, "total_plays": 10, "years": ["2024"]}' > docs/data/summary.json
           echo '{"2024": {"ms": 3600000, "plays": 10, "hours": 1.0}}' > docs/data/listening_by_year.json
           echo '{"2024": [{"artist": "Sample Artist", "plays": 5, "hours": 0.5}]}' > docs/data/top_artists_by_year.json
           echo '{"2024": [{"artist": "Sample Artist", "track": "Sample Track", "plays": 3, "hours": 0.3}]}' > docs/data/top_tracks_by_year.json
           echo "date,hours,plays" > docs/data/listening_daily.csv
           echo "2024-01-01,0.1,1" >> docs/data/listening_daily.csv
        fi
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
         - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
         path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
